### ISSUE TITLE
Pick coke can variants.

### ISSUE THREAD

**Issue by HuFY-dev** [simpler-env/SimplerEnv#13]
I saw in your eval scripts for pick coke can: [`declare -a coke_can_options_arr=("lr_switch=True" "upright=True" "laid_vertically=True")`](https://github.com/simpler-env/SimplerEnv/blob/bcf62960dc9d95501cf36dc8c64d2128e9b10e09/scripts/rt1_pick_coke_can_visual_matching.sh#L11).

In Table IV in your paper, there's `Horizontal Laying`, `Vertical Laying`, `Standing` three variants. Does `lr_switch=True` correspond to the `Horizontal Laying` variant? If so, does that mean you didn't evaluate the default setting where `"lr_switch=False, upright=False, laid_vertically=False"`?

**Comment by xuanlinli17** [comment]
"lr_switch" is coke can oriented by 180 degrees to match real eval's "horizontally laying" setting.

If you set "lr_switch=False, upright=False, laid_vertically=False" args to False, then the coke can will be oriented randomly. There is no "default setting". The purpose of our experiments is to draw correlation with real-world evaluations under a similar setup, and 3 default orientations (horizontal / vertical laying, standing) with a "grid sweep" over coke can positions already covers many variations.

**Comment by HuFY-dev** [comment]
Thanks for the clarification!

**Comment by erjiaxiao** [comment]
Hello @xuanlinli17, I wonder is it possible to change the position of the Coke can in the simulator?

**Comment by xuanlinli17** [comment]
For xy positions, yes (see example scripts)
