### ISSUE TITLE
Eval code for RT-2-X?

### ISSUE THREAD

**Issue by HuFY-dev** [simpler-env/SimplerEnv#14]
Hi, I saw that you have RT-2-X results in the paper. Do you plan on releasing the code to evaluate RT-2-X on SimplerEnv?

**Comment by xuanlinli17** [comment]
RT-2-X has a very similar evaluation code as RT-1(-X) but requires an API key to access the model. Thus, until Google publicly releases the RT-2-X API, I can't release the code yet.

**Comment by HuFY-dev** [comment]
Got it!

**Comment by hahans** [comment]
Hi,how did you get RT-2-X API key?I want to use RT-2-X,but I can't find any model in internet.

**Comment by xuanlinli17** [comment]
Unfortunately I don't think Google decides to release it yet...
