### ISSUE TITLE
Octo behaves strange

### ISSUE THREAD

**Issue by Udntknwme** [simpler-env/SimplerEnv#19]
Hi, thanks for the great work! 

I'm using your work to try to reproduce and analyze octo and openvla.

I'm not fully familiar with the code yet, and I just ran through the provided octo test script. openvla can behave normally, although the success rate is not very high. But the octo performance feels like an error in the output mapping to the simulation engine. Noted that I have not made any changes to the code yet.

I would like to ask where to start checking this problem?

Thanks.

https://github.com/user-attachments/assets/cb437665-8c62-4281-a951-5c7ad86a4ea1

**Comment by xuanlinli17** [comment]
Octo behavior is normal. It staggers very frequently under (unseen) simulation scene backgrounds. If you put a real background that matches the training, then its behavior is better

**Comment by Udntknwme** [comment]
I tested different backgrounds and different settings and found that Octo's performance was very different. Thanks for your guidance.

**Comment by yxchng** [comment]
@Udntknwme How do you test different backgrounds?
