### ISSUE TITLE
what are the differences between the different urdfs?

### ISSUE THREAD

**Issue by yxchng** [simpler-env/SimplerEnv#22]
https://github.com/simpler-env/SimplerEnv/blob/2a0389226175853baeaa76d53ca0e3a48eaf238d/scripts/octo_move_near_visual_matching.sh#L17

**Comment by xuanlinli17** [comment]
They are differently colored (using gnu image manipulation bucket paint tool) based on different real-world images from different tasks to reflect the variations in arm color during manipulation.
