### ISSUE TITLE
[svulkan2] [error] GLFW error: X11: Failed to open display

### ISSUE THREAD

**Issue by armstronglzh** [simpler-env/SimplerEnv#24]
hi,I met this error when I test :
python simpler_env/simple_inference_visual_matching_prepackaged_envs.py
Maybe I can't see the operation window because of this ,how can I solve this ,and also the warning:
[svulkan2] [warning] Continue without GLFW.

**Comment by armstronglzh** [comment]
I solve this error to set  os.environ["DISPLAY"] = ":1" in the py file,but I still can't see the whole progress in a display window,is it normal or is there something else I don't set correctly.

**Comment by xuanlinli17** [comment]
This is normal. You can ignore the warning.

**Comment by armstronglzh** [comment]
> This is normal. You can ignore the warning.

I mean that after running the program, a window should appear to display the robot's running process,but I don't see any window.Is it normal or the program is just like this with no window displaying

**Comment by xuanlinli17** [comment]
The script does not display a window. Instead, evaluation videos are saved. Please see the script for more details.
