### ISSUE TITLE
How to convert RT-1-X action to Octo action

### ISSUE THREAD

**Issue by MasterXiong** [simpler-env/SimplerEnv#40]
Hi, 

I wanted to use successful episodes collected by RT-1-X in the google robot envs as demos to fine-tune an Octo model. I was wondering that how could I convert the raw action generated by RT-1-X to the corresponding raw action of Octo? As I note that the inference function for the two models are different in `simpler` code, which may indicate that they do not use the same action space and some coordinates transformation is required here? Thanks!

**Comment by xuanlinli17** [comment]
Just compare the 2 inference code. I think only the gripper is different.

**Comment by MasterXiong** [comment]
Thanks! But I noticed that for the actions dimensions of orientations, RT-1 uses axis angle representation for google robot tasks, and roll, pitch, yaw representation for widowx tasks ([link](https://github.com/simpler-env/SimplerEnv/blob/0b13b698138576c449f8853c99b04202e3c04952/simpler_env/policies/rt1/rt1_model.py#L45)). And Octo seems to use roll, pitch, yaw for both kinds of robots. So should I transform axangle to euler for google robot?

**Comment by xuanlinli17** [comment]
I think so.
