### ISSUE TITLE
AttributeError: 'TimeLimit' object has no attribute 'get_language_instruction'

### ISSUE THREAD

**Issue by branyang02** [simpler-env/SimplerEnv#44]
https://colab.research.google.com/github/simpler-env/SimplerEnv/blob/main/example.ipynb no longer works.

The error is:
AttributeError: 'TimeLimit' object has no attribute 'get_language_instruction'

<img width="747" alt="image" src="https://github.com/user-attachments/assets/acbb59cb-fae1-4c06-bbd5-27b4c0e01c7e">

**Comment by younik** [comment]
@branyang02 This is due to Gymnasium 1.0; use `env.unwrapped.get_language_instruction()` instead, or downgrade Gymnasium.

**Comment by xuanlinli17** [comment]
Forced gymnasium < 1.0 in latest commit

**Comment by LukeLIN-web** [comment]
Just for a note for others like me . https://github.com/simpler-env/SimplerEnv/commit/f3035e0135d102587f2acd25e5cada3189c06d0b    


You  can just run `pip install gymnasium==0.28.1`
