### ISSUE TITLE
Success rate about grasping objects in bridge

### ISSUE THREAD

**Issue by cheryyunl** [simpler-env/SimplerEnv#48]
Hi, thanks for providing detailed evaluation scripts.

I have a small question, when we evaluate models on bridge environment, how can we calculate the success rate of grasping objects like spoon and carrot? (which as shown in Figure 7)
I think maybe we need to change the maniskill_evaluator? I'm not sure

Thank you for your help!

Best,

**Comment by xuanlinli17** [comment]
This is already reported in the names of the saved evaluation videos, if you run `scripts/*`; the results are also extracted via `https://github.com/simpler-env/SimplerEnv/blob/main/tools/calc_metrics_evaluation_videos.py#L930`
