### ISSUE TITLE
New object metadata

### ISSUE THREAD

**Issue by abadithela** [simpler-env/SimplerEnv#53]
Hi,

I am setting up a custom environment following instructions given here: [https://github.com/simpler-env/SimplerEnv/blob/main/ADDING_NEW_ENVS_ROBOTS.md](https://github.com/simpler-env/SimplerEnv/blob/main/ADDING_NEW_ENVS_ROBOTS.md).

On bullet 7 of adding new environments, it says: 

"Our environments load metadata json files for the object assets (in ManiSkill2_real2sim/data/custom/info_*.json). Based on your environment implementation, fill in the metadata for each new object asset in existing json files or create new json files."

An example of these info.json files has object descriptions of their bounding box, scale, and density: 

`"bridge_spoon_generated_modified": {
    "bbox": {
      "min": [
        -0.07,
        -0.0173,
        -0.013021
      ],
      "max": [
        0.07,
        0.0173,
        0.013021
      ]
    },
    "scales": [
      1.0
    ],
    "density": 1200
  },`
  
  If I should add a new object, where do I get the bbox characteristics from? Is there a tool that can easily provide this?
  
  Thanks!

**Comment by xuanlinli17** [comment]
Hi, you can measure them using blender (press N to toggle object dimension properties), or get the bbox using trimesh.
