### ISSUE TITLE
ImportError: cannot import name 'sa' from 'simulated_annealing'

### ISSUE THREAD

**Issue by revquiet** [simpler-env/SimplerEnv#57]
I encountered an issue when trying to import sa from the simulated_annealing module in `tools/sysid/sysid.py.` The import statement fails so i  installed the module using pip:
```
pip install simulated-annealing
```
the following error arises:
```
cannot import name 'sa' from 'simulated_annealing' (/home/test/miniconda3/envs/simpler_env/lib/python3.10/site-packages/simulated_annealing/__init__.py) 
  File "/home/test/Code/git_repo/SimplerEnv/tools/sysid/sysid.py", line 11, in <module>
    from simulated_annealing import sa
ImportError: cannot import name 'sa' from 'simulated_annealing' (/home/test/miniconda3/envs/simpler_env/lib/python3.10/site-packages/simulated_annealing/__init__.py)
```
I am using version 0.4.0 of simulated-annealing, Upon inspecting the __init__.py file in the installed module directory, I noticed there is no reference to sa, nor any indication of its availability. If sa is not part of the package, it would be very helpful if the documentation could clarify its usage or provide a module of sa to guide me on how to achieve similar functionality.

Thank you for your help and guidance!

**Comment by revquiet** [comment]
When I modified the code as follows:
```
import simulated_annealing as sa
```

I encountered an error indicating that the sa module does not have the minimize() method. How can I correctly import this module and perform the corresponding system identification?
```
opt = sa.minimize(
    opt_fxn,
    init_action,
    opt_mode="continuous",
    step_max=2000,
    t_max=1.5,
    t_min=0,
    bounds=[[0, 1]] * (len(init_stiffness) * 2),
)
```

Could you please advise on the appropriate steps to resolve this issue?

**Comment by xuanlinli17** [comment]
Did you `pip install git+https://github.com/nathanrooy/simulated-annealing`?

**Comment by revquiet** [comment]
Thank you for your response. Your solution indeed resolved my issue. During the process of identifying the system, I used my own dataset instead of utilizing RT-1 and OCTO, thus skipping some crucial related steps.
