### ISSUE TITLE
Will you release more environments?

### ISSUE THREAD

**Issue by zhiyuan-zhang0206** [simpler-env/SimplerEnv#9]
Dear researchers,
Thanks so much for your hard work. I can imagine the huge engineering efforts required here.
May I ask if there are any plans to replicate more environments?

**Comment by xuanlinli17** [comment]
Currently there are some efforts to build more environments like the Track 2 of ICML-MFM-EAI challenge (https://icml-mfm-eai.github.io/challenges/#TRACK2) which will use real-to-sim environments based on ManiSkill3 for evaluation; for our environments @StoneT2000 is migrating them to ManiSkill3 first so it will take a while.
